baseURL = "/"
languageCode = "en-us"
title = "JAMstack Themes"
theme = "jamstackthemes"
paginate = 30
enableGitInfo = true

[taxonomies]
  ssg = "ssg"
  cms = "cms"
  css = "css"

[params]
    google_analytics_id = "UA-122379868-3"
    description = "A list of Themes and Starters for JAMstack Sites."
    enable_badge_staticgen = false
    enable_badge_headlesscms = false
    enable_badge_official = true

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]

# Main Menu
[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 1
